# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b19bf7a673dddcb66d23a20f2afd44215388d6102fe4c5cc58d870a20d65f54d2c1b75bbe5ea28fa71e8d64cfc8be5c7b87582729e60b24c13ae16c1bb434700

test:
  secret_key_base: f34983e85dcac9259edf10caa035783bd2a374908a94a13c6effbbad354e2be0a9b51c901361cf376ee61135895347c307de3bc18a694814c4528421f541cd82

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
